# Generated by Django 5.2 on 2025-12-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                upload_to="images/store/<django.db.models.query_utils.DeferredAttribute object at 0x106d5b740>/products/"
            ),
        ),
    ]
