# Generated by Django 5.2 on 2025-12-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                upload_to="images/store/<django.db.models.query_utils.DeferredAttribute object at 0x1079f3a40>/products/"
            ),
        ),
    ]
