# Generated by Django 5.2 on 2025-12-19 07:48

import catalogue.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0004_alter_product_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "verbose_name": "product category",
                "verbose_name_plural": "product categories",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                upload_to=catalogue.utils.product_image_upload_path
            ),
        ),
    ]
