# Generated by Django 5.2 on 2025-12-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nfc", "0002_producttag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nfctag",
            name="authority",
        ),
        migrations.RemoveField(
            model_name="nfctag",
            name="name",
        ),
        migrations.AddField(
            model_name="nfctag",
            name="number",
            field=models.PositiveIntegerField(default=0, verbose_name="number"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nfctag",
            name="serial_number",
            field=models.CharField(
                default=None, max_length=100, verbose_name="serial_number"
            ),
            preserve_default=False,
        ),
    ]
