# Generated by Django 5.2 on 2025-12-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nfc", "0003_remove_nfctag_authority_remove_nfctag_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nfctag",
            name="is_free",
            field=models.BooleanField(default=True, verbose_name="is free"),
        ),
    ]
