# Generated by Django 5.2 on 2025-12-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nfc", "0004_alter_nfctag_is_free"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nfctag",
            name="serial_number",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="serial_number"
            ),
        ),
    ]
