# Generated by Django 5.2 on 2025-12-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nfc", "0005_alter_nfctag_serial_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nfctag",
            name="number",
        ),
    ]
