# Generated by Django 5.2 on 2025-12-20 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nfc", "0006_remove_nfctag_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="nfctag",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created_at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nfctag",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated_at"),
        ),
    ]
