# Generated by Django 5.2 on 2025-12-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nfc", "0007_nfctag_created_at_nfctag_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nfctag",
            name="serial_number",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="serial number"
            ),
        ),
    ]
