# Generated by Django 5.2 on 2025-12-21 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0006_product_uuid"),
        ("nfc", "0008_alter_nfctag_serial_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttag",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="catalogue.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="producttag",
            name="tag",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="nfc.nfctag",
                verbose_name="tag",
            ),
        ),
    ]
