# Generated by Django 5.2 on 2025-12-22 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nfc", "0009_alter_producttag_product_alter_producttag_tag"),
        ("store", "0007_alter_storeuser_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="nfctag",
            name="store",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="tags",
                to="store.store",
            ),
            preserve_default=False,
        ),
    ]
