# Generated by Django 5.2 on 2025-11-03 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="store.state",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="stores",
                to="store.city",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="image",
            field=models.ImageField(
                upload_to="images/store/<django.db.models.fields.CharField>"
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="stores",
                to="store.state",
            ),
        ),
        migrations.AlterField(
            model_name="storeuser",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="users",
                to="store.store",
            ),
        ),
        migrations.AlterField(
            model_name="storeuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="stores",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
