# Generated by Django 5.2 on 2025-12-19 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_city_state_alter_store_city_alter_store_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "city", "verbose_name_plural": "cities"},
        ),
    ]
