# Generated by Django 5.2 on 2025-12-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_city_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="phone1",
            field=models.CharField(max_length=11, verbose_name="Phone number 1"),
        ),
        migrations.AlterField(
            model_name="store",
            name="phone2",
            field=models.CharField(max_length=11, verbose_name="Phone number 2"),
        ),
    ]
