# Generated by Django 5.2 on 2025-12-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_store_phone1_alter_store_phone2"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeuser",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
    ]
