# Generated by Django 5.2 on 2025-12-21 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_storeuser_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storeuser",
            name="is_staff",
        ),
    ]
