# Generated by Django 5.2 on 2025-12-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_owner",
            field=models.BooleanField(default=False, verbose_name="is owner"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="national_id",
            field=models.CharField(default=0, unique=True, verbose_name="national id"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="is staff"),
        ),
    ]
