# Generated by Django 5.2 on 2025-12-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_customuser_is_owner_customuser_national_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="national_id",
            field=models.CharField(verbose_name="national id"),
        ),
    ]
