# Generated by Django 5.2 on 2025-12-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_customuser_national_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="national_id",
        ),
    ]
