# Generated by Django 5.2 on 2025-12-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_customuser_national_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_owner",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
    ]
